sudo: required
services:
  - docker

before_install:
  - docker build -t hoanghiep2004hy/docker-travis -f Dockerfile.dev .

script:
  - docker run hoanghiep2004hy/docker-travis npm run test -- --coverage